// <auto-generated />
using System;
using Library.Infrasturcture.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryASPNET_Core.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210804060642_initDB2")]
    partial class initDB2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Library.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author_");
                });

            modelBuilder.Entity("Library.Domain.Models.Author_Book", b =>
                {
                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.Property<int>("Author_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Book_Id", "Author_Id");

                    b.HasIndex("Author_Id");

                    b.ToTable("Author_Book_");
                });

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reader_Id")
                        .HasColumnType("int");

                    b.Property<int>("Shelf_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Reader_Id");

                    b.HasIndex("Shelf_Id");

                    b.ToTable("Book_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoPath = "infjoke.jpg",
                            Reader_Id = 1,
                            Shelf_Id = 1,
                            TakeDate = new DateTime(2021, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Бесконечная шутка"
                        });
                });

            modelBuilder.Entity("Library.Domain.Models.Book_category", b =>
                {
                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Book_Id", "Category_Id");

                    b.HasIndex("Category_Id");

                    b.ToTable("Book_Category_");
                });

            modelBuilder.Entity("Library.Domain.Models.Book_tag", b =>
                {
                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.Property<int>("Tag_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Book_Id", "Tag_Id");

                    b.HasIndex("Tag_Id");

                    b.ToTable("Book_Tag_");
                });

            modelBuilder.Entity("Library.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Детектив"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Фэнтези"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Приключения"
                        },
                        new
                        {
                            Id = 5,
                            Name = "История"
                        });
                });

            modelBuilder.Entity("Library.Domain.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reader_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1996, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Full_Name = "Иванов Иван Иванович",
                            RegistrationDate = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1992, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Full_Name = "Квашнин Петр Михайлович",
                            RegistrationDate = new DateTime(2021, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2001, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Full_Name = "Петрухин Александр Андреевич",
                            RegistrationDate = new DateTime(2021, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Library.Domain.Models.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shelf_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        });
                });

            modelBuilder.Entity("Library.Domain.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "#war"
                        },
                        new
                        {
                            Id = 2,
                            Name = "#love"
                        },
                        new
                        {
                            Id = 3,
                            Name = "#KILLA"
                        });
                });

            modelBuilder.Entity("Library.Domain.Models.Author_Book", b =>
                {
                    b.HasOne("Library.Domain.Models.Author", "AuthorsObj")
                        .WithMany("Author_BookObj")
                        .HasForeignKey("Author_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Book", "BooksObj")
                        .WithMany("Author_BookObj")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorsObj");

                    b.Navigation("BooksObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.HasOne("Library.Domain.Models.Reader", "ReaderObj")
                        .WithMany("BookObj")
                        .HasForeignKey("Reader_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Shelf", "ShelfObj")
                        .WithMany("BookObj")
                        .HasForeignKey("Shelf_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReaderObj");

                    b.Navigation("ShelfObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Book_category", b =>
                {
                    b.HasOne("Library.Domain.Models.Book", "BookObj")
                        .WithMany("Book_CategoryObj")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Category", "CategoryObj")
                        .WithMany("Book_CategoryObj")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookObj");

                    b.Navigation("CategoryObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Book_tag", b =>
                {
                    b.HasOne("Library.Domain.Models.Book", "BookObj")
                        .WithMany("Book_TagObj")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Tag", "TagObj")
                        .WithMany("Book_TagObj")
                        .HasForeignKey("Tag_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookObj");

                    b.Navigation("TagObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Author", b =>
                {
                    b.Navigation("Author_BookObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.Navigation("Author_BookObj");

                    b.Navigation("Book_CategoryObj");

                    b.Navigation("Book_TagObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Category", b =>
                {
                    b.Navigation("Book_CategoryObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Reader", b =>
                {
                    b.Navigation("BookObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Shelf", b =>
                {
                    b.Navigation("BookObj");
                });

            modelBuilder.Entity("Library.Domain.Models.Tag", b =>
                {
                    b.Navigation("Book_TagObj");
                });
#pragma warning restore 612, 618
        }
    }
}
