// <auto-generated />
using System;
using Library.Infrasturcture.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryASPNET_Core.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210802023042_edit_model_db")]
    partial class edit_model_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryASPNET_Core.Models.Authors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors_");
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Authors_Books", b =>
                {
                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.Property<int>("Author_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Book_Id", "Author_Id");

                    b.HasIndex("Author_Id");

                    b.ToTable("Authors_Books_");
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reader_Id")
                        .HasColumnType("int");

                    b.Property<int>("Shelf_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Reader_Id");

                    b.HasIndex("Shelf_Id");

                    b.ToTable("Books_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoPath = "C:\\Users\\semyo\\Desktop\\images\\1",
                            Reader_Id = 1,
                            Shelf_Id = 1,
                            TakeDate = new DateTime(2021, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Бесконечная шутка"
                        });
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Books_category", b =>
                {
                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Book_Id", "Category_Id");

                    b.HasIndex("Category_Id");

                    b.ToTable("Books_Categories_");
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Books_tags", b =>
                {
                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.Property<int>("Tag_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Book_Id", "Tag_Id");

                    b.HasIndex("Tag_Id");

                    b.ToTable("Books_Tags_");
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Детектив"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Фэнтези"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Приключения"
                        },
                        new
                        {
                            Id = 5,
                            Name = "История"
                        });
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Readers_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1996, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Full_Name = "Иванов Иван Иванович",
                            RegistrationDate = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1992, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Full_Name = "Квашнин Петр Михайлович",
                            RegistrationDate = new DateTime(2021, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2001, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Full_Name = "Петрухин Александр Андреевич",
                            RegistrationDate = new DateTime(2021, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Shelves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shelves_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        });
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "#war"
                        },
                        new
                        {
                            Id = 2,
                            Name = "#love"
                        },
                        new
                        {
                            Id = 3,
                            Name = "#KILLA"
                        });
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Authors_Books", b =>
                {
                    b.HasOne("LibraryASPNET_Core.Models.Authors", "AuthorsObj")
                        .WithMany("Authors_BooksObj")
                        .HasForeignKey("Author_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryASPNET_Core.Models.Books", "BooksObj")
                        .WithMany("Author_BooksObj")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Books", b =>
                {
                    b.HasOne("LibraryASPNET_Core.Models.Reader", "ReaderObj")
                        .WithMany("BooksObj")
                        .HasForeignKey("Reader_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryASPNET_Core.Models.Shelves", "ShelfObj")
                        .WithMany("BooksObj")
                        .HasForeignKey("Shelf_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Books_category", b =>
                {
                    b.HasOne("LibraryASPNET_Core.Models.Books", "BooksObj")
                        .WithMany("Books_CategoriesObj")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryASPNET_Core.Models.Category", "CategoriesObj")
                        .WithMany("Books_CategoriesObj")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryASPNET_Core.Models.Books_tags", b =>
                {
                    b.HasOne("LibraryASPNET_Core.Models.Books", "BooksObj")
                        .WithMany("Books_TagObj")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryASPNET_Core.Models.Tags", "TagsObj")
                        .WithMany("Books_TagObj")
                        .HasForeignKey("Tag_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
